---
title: "Prophet"
author: "Peter Li"
date: "2017/12/4"
output: html_document
---

```{r}
#packages
library(data.table)
library(lubridate)
library(date)
library(reshape2)
library(forecast)
library(doMC)
library(foreach)
library(dplyr)
library(prophet)
```


```{r, echo=FALSE}
setwd("~/ADS/fall2017-project5-group1/lib/")
train_sub <- fread("../output/subtrain&validation/subtrain.csv")
train_valid <- fread("../output/subtrain&validation/validation.csv")

train_sub <- train_sub[, c('date','store_item_nbr', 'unit_sales')]

train_sub_wide <- dcast(train_sub, store_item_nbr ~ date, mean, value.var = "unit_sales", fill = 0)
train_ts <- ts(train_sub_wide[,-1], frequency = 7) 

fcst_intv = length(unique(train_valid$date))  # number of days of forecast in the validation set
fcst_matrix <- matrix(NA,nrow=nrow(train_ts),ncol=fcst_intv)

# forecast the sales in validation set
changepoint.scale <- seq(0.1, 2, by = 0.2)
valid_score <- rep(NA, length(changepoint.scale))
```


```{r}
for (j in 1:length(changepoint.scale)){
  print(paste0("j=",j))
  lam <- changepoint.scale[j]
  # fcst_matrix <- foreach(i=1:nrow(train_ts),.combine=rbind, .packages=c("forecast")) %dopar% { 
  #   tmp = data.frame(ds = colnames(train_ts),
  #                    y = train_ts[i,])
  #   m <- prophet(tmp, changepoint.prior.scale = lam)
  #   future <- make_future_dataframe(m, periods = fcst_intv,freq = "day")
  # 
  #   forecast <- tail(predict(m, future)$yhat,fcst_intv)
  #   actual_ = train_valid[which(train_valid$store_item_nbr == train_sub_wide$store_item_nbr[i])]
  #   actual_ = actual_[,-1] %>%
  #     group_by(date) %>%
  #     summarise(unit_sales = sum(unit_sales),
  #               perishable = max(perishable))
  #   
  #   actual = actual_$unit_sales[order(actual_$date,decreasing = F)]
  #   
  #   w <- ifelse(actual_$perishable[order(actual_$date,decreasing = F)] == 0, 1, 1.25)
  #   
  #   valid_score[i] <- sqrt(sum(w * (log(forecast + 1) - log(actual + 1))^2)/sum(w))
  #   
  # }
  
  n <- nrow(train_ts)
  pb <- txtProgressBar(0, n, style = 2)
  
  registerDoMC(detectCores()-1)

  fcst_matrix <- foreach(i=1:nrow(train_ts),.combine=rbind, .packages=c("prophet","forecast")) %dopar% { 
    setTxtProgressBar(pb, i)
    tmp = data.frame(ds = colnames(train_ts),
                     y = train_ts[i,])
    m <- prophet(tmp, changepoint.prior.scale = lam)
    future <- make_future_dataframe(m, periods = fcst_intv,freq = "day")

    fcst_matrix <- tail(predict(m, future)$yhat,fcst_intv)
  }
  
  colnames(fcst_matrix) <- as.character(seq(from = as.Date("2016-04-16"), 
                                          to = as.Date("2016-08-15"), 
                                          by = 'day'))
  fcst_df <- as.data.frame(cbind(train_sub_wide[, 1], fcst_matrix)) 
  colnames(fcst_df)[1] <- "store_item_nbr"

  fcst_df_long <- melt(fcst_df, id = 'store_item_nbr', 
                                variable.name = "fcst_date", 
                                value.name = 'unit_sales')
  fcst_df_long$store_item_nbr <- as.character(fcst_df_long$store_item_nbr)
  fcst_df_long$fcst_date <- as.Date(parse_date_time(fcst_df_long$fcst_date,'%y-%m-%d'))
  fcst_df_long$unit_sales <- as.numeric(fcst_df_long$unit_sales)
  colnames(fcst_df_long)[3] <- "sales_pred"

  train_valid$date <- as.Date(parse_date_time(train_valid$date, '%y-%m-%d'))
  train_comb <- left_join(train_valid[,-1], fcst_df_long, 
                        c("store_item_nbr" = "store_item_nbr", 'date' = 'fcst_date'))
  train_comb$sales_pred[train_comb$sales_pred < 0] <- 0
  train_comb$unit_sales[train_comb$unit_sales < 0] <- 0

  train_save <- train_comb[,c(1:6,8,ncol(train_comb))]
  save(train_save, file = paste0("../output/prophet_changepoint_",changepoint.scale[i],".RData"))
  # calculate the score of accuracy prediction on validation set
  w <- ifelse(train_comb$perishable == 0, 1, 1.25)
  valid_score[j] <- sqrt(sum(w * (log(train_comb$sales_pred + 1) - log(train_comb$unit_sales + 1))^2)/sum(w))
}
save(valid_score, file = "../output/prophet_valid_score.RData")
```


```{r}
train_sub2 = rbind(train_sub,train_valid[,c('date','store_item_nbr', 'unit_sales')])
train_sub_wide2 <- dcast(train_sub2, store_item_nbr ~ date, mean, value.var = "unit_sales", fill = 0)

train_ts2 <- ts(train_sub_wide2[,-1], frequency = 7) 

# performance on test dataset
test <-fread('../output/combined_test.csv')
test$date <- as.Date(parse_date_time(test$date,'%y-%m-%d'))

fcst_intv1 = 365  # number of days of forecast in the test set
fcst_matrix1 <- matrix(NA,nrow=nrow(train_ts2),ncol=fcst_intv1)

# forecast the sales in test set
registerDoMC(detectCores()-1)
fcst_matrix1 <- foreach(i=1:nrow(train_ts2),.combine=rbind, .packages=c("prophet","forecast")) %dopar% { 
  tmp = data.frame(ds = colnames(train_ts2),
                     y = train_ts2[i,])
    m <- prophet(tmp, changepoint.prior.scale = changepoint.scale[which.min(valid_score)])
    future <- make_future_dataframe(m, periods = fcst_intv1,freq = "day")

    fcst_matrix1 <- tail(predict(m, future)$yhat,fcst_intv1)
}
colnames(fcst_matrix1) <- as.character(seq(from = as.Date("2016-08-16"), 
                                          to = as.Date("2017-08-15"), 
                                          by = 'day'))
fcst_df1 <- as.data.frame(cbind(train_sub_wide2[, 1], fcst_matrix1)) 
colnames(fcst_df1)[1] <- "store_item_nbr"

fcst_df_long1 <- melt(fcst_df1, id = 'store_item_nbr', 
                              variable.name = "fcst_date", 
                              value.name = 'unit_sales')
fcst_df_long1$store_item_nbr <- as.character(fcst_df_long1$store_item_nbr)
fcst_df_long1$fcst_date <- as.Date(parse_date_time(fcst_df_long1$fcst_date,'%y-%m-%d'))
fcst_df_long1$unit_sales <- as.numeric(fcst_df_long1$unit_sales)
colnames(fcst_df_long1)[3] <- "sales_pred"

test_comb <- left_join(test, fcst_df_long1, 
                        c("store_item_nbr" = "store_item_nbr", 'date' = 'fcst_date'))
test_comb$sales_pred[test_comb$sales_pred < 0] <- 0
test_comb$unit_sales[test_comb$unit_sales < 0] <- 0

save(test_comb, file = "../output/prophet_test_comb.RData")
# calculate the score of accuracy prediction on validation set
w1 <- ifelse(test_comb$perishable == 0, 1, 1.25)
test_score <- sqrt(sum(w1 * (log(test_comb$sales_pred + 1) - log(test_comb$unit_sales + 1))^2)/sum(w1))
```