---
title: "RF"
author: "Shiqi Duan"
date: "2017/12/4"
output: html_document
---

```{r}
library(caret)
library(randomForest)
library(doParallel)

cores <- 3
cl <- makePSOCKcluster(cores)
registerDoParallel(cl)

dataset <- read.csv("/home/anonimo/Modelli/total_merge.csv", header=TRUE)
dati <- data.frame(dataset)
attach(dati)


trainSet <- dati[2:107570,]
testSet <- dati[107570:480343,]

# 3 times cross validation.
my_control <- trainControl(method = "cv", number = 3 )

attach(train.data)

my_forest <- train(unit_sales ~ .,
                   data = train.data,
                   method = "parRF",
                   ntree = 250,
                   trControl=my_control)


```

```{r, echo=FALSE}
foreach_forest <- foreach(ntree=rep(250, cores), 
                          .combine=combine, 
                          .multicombine=TRUE, 
                          .packages="randomForest") %dopar%
  randomForest(unit_sales ~ ., 
                   data = train.data, ntree=250)
```

for Jodan use
```{r}
library(randomForest)

# process the whole train data so they can be used in RF smoothly
train$onpromotion <- ifelse(train$onpromotion == TRUE, 1, 0)
train$unit_sales[train$unit_sales < 0] <- 0
  
train.rf <- train[,-c(1,3,4,8,16,17,19)]
train.rf$celebrated[is.na(train.rf$celebrated)] <- FALSE
train.rf$family <- factor(train.rf$family)
train.rf$celebrated <- factor(train.rf$celebrated)

set.seed(2)
n_train <- nrow(train.rf)
K <- 5
n.fold <- floor(n_train/K)
s <- sample(rep(1:K, c(rep(n.fold, K-1), n_train-(K-1)*n.fold)))
  
n_trees <- seq(500, 1000, 100)
fscore.rf <- rep(NA,K)
fopt.mtry <- rep(NA,K)
score.rf <- rep(NA, length(n_trees))
opt.mtry <- rep(NA, length(n_trees))
  
# run the RF on random sampled data
for (j in 1:length(n_trees)){
  for(i in 1:K){
    train.data <- train.rf[s == i,]
    test.data <- train.rf[s == 100-i,]

    fit <- tuneRF(train.data[,-"unit_sales"], train.data$unit_sales,
                  ntreeTry = n_trees[j], 
                  doBest = TRUE)
 
    # Get the 'mtry' for trained model
    fopt.mtry[i] <- fit$mtry
    pred <- predict(fit, test.data[,-c("unit_sales")])
    w <- ifelse(test.data$perishable == 0, 1, 1.25)
    fscore.rf[i] <- sqrt(sum(w * (log(pred + 1) - log(test.data$unit_sales + 1))^2)/sum(w))
  }
  # Get the lowest error rate of cross validation
  score.rf[j] <- mean(fscore.rf)
  opt.mtry[j] <- fopt.mtry[which.min(fscore.rf)]
  save(score.rf, file="../output/RF_score100.RData")
  save(opt.mtry, file="../output/RF_mtry.RData")
}
```
